import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { dbConnect } from "@/service/mongoose";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "PrepForge : prepare for your dream",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  // ✅ DB connection (kept as per your current approach)
  await dbConnect();

  return (
    <html
      lang="en"
      className={cn(`${inter.variable} h-full antialiased`)}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}